name: time_machine_message
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_riverpod: ^2.3.2
  flutter_secure_storage: ^8.0.0
  go_router: ^6.5.0
  google_fonts: ^4.0.3
  intl: ^0.17.0
  sizer: ^2.0.15
  state_notifier: ^0.7.2+1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

  import_sorter: ^4.6.0
  logger: ^1.3.0
  pubspec_dependency_sorter: ^1.0.3
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon/
    - assets/images/icon/social/

flutter_intl:
  enabled: true
flutter_gen:
  output: lib/generated/assets/
